<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Celsius.png" />
    <None Remove="Resources\Fahrenheit.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="Unity.Container" Version="5.11.11" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Celsius.png" />
    <Resource Include="Resources\Fahrenheit.jpg" />
  </ItemGroup>

</Project>
