name: Temperature Converter CI/CD 

on: 
  push:
    branches:   
      - "Temperature-Converter"
  pull_request:
    branches:
      - "Temperature-Converter"  
  
jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
      - uses: actions/checkout@v2
     
      - name: Test Connectivity
        run: |
             Invoke-WebRequest -Uri "http://192.168.1.224:9091/metrics" 
      - name: Test connection to Prometheus
        run: |
          $body = "# TYPE custom_metric_name gauge`ncustom_metric_name 444`n"
          Invoke-WebRequest -Uri "http://192.168.1.224:9091/metrics/job/github_actions" -Method POST -Body $body
        shell: pwsh

      - name: Capture start time
        run: echo "START_TIME=$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV
        shell: pwsh
        
      - name: Build WPF application
        run: ./Temperature_Converter/build.ps1
        working-directory: ./

      - name: Verify output directory
        run: ls ./Temperature_Converter/output

      - name: Upload build artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./Temperature_Converter/output
          
      - name: Capture end time
        run: echo "END_TIME=$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV
        shell: pwsh

      - name: Calculate execution time
        run: |
              $start = [datetime]$env:START_TIME
              $end = [datetime]$env:END_TIME
              $duration = ($end - $start).TotalSeconds
              echo "Execution Time: $duration seconds"
              $body = "# TYPE workflow_execution_time gauge`nworkflow_execution_time_seconds $duration`n"
              Invoke-WebRequest -Uri "http://192.168.1.224:9091/metrics/job/github_actions" -Method POST -Body $body
              shell: pwsh
         
      - name: Notify Success
        if: success()
        run: |
          $branch = $env:GITHUB_REF -replace 'refs/heads/', ''
          $commit = $env:GITHUB_SHA
          $payload = '{"text": "✅ Build succeeded for branch: ' + $branch + ' \n Commit: ' + $commit + '"}'
          Invoke-RestMethod -Uri "${{ secrets.WEBHOOK_GITHUB_SLACK }}" -Method Post -Body $payload -ContentType 'application/json'
        shell: pwsh

      - name: Notify Failure
        if: failure()
        run: |
          $payload = '{"text": "❌ Build failed! Check logs for details."}'
          Invoke-RestMethod -Uri "${{ secrets.WEBHOOK_GITHUB_SLACK }}" -Method Post -Body $payload -ContentType 'application/json'
        shell: pwsh

  test:
    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./Temperature_Converter/output

      - name: Run tests
        run: ./Temperature_Converter_UnitTest/UnitTest.ps1

      - name: List TestResults directory
        run: ls ./Temperature_Converter_UnitTest/TestResults

      - name: Upload unit test results 
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: ./Temperature_Converter_UnitTest/TestResults/junit-unit-test-results.xml
          if-no-files-found: warn

      - name: Notify Test Success
        if: success()
        run: |
          $payload = '{"text": "✅ Tests passed successfully!"}'
          Invoke-RestMethod -Uri "${{ secrets.WEBHOOK_GITHUB_SLACK }}" -Method Post -Body $payload -ContentType 'application/json'
        shell: pwsh

      - name: Notify Test Failure
        if: failure()
        run: |
          $payload = '{"text": "❌ Tests failed! Check logs for details."}'
          Invoke-RestMethod -Uri "${{ secrets.WEBHOOK_GITHUB_SLACK }}" -Method Post -Body $payload -ContentType 'application/json'
        shell: pwsh

  deploy:
    needs: 
      - build
      - test
    runs-on: [self-hosted, windows]

    steps:
      - uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ${{ github.workspace }}/output

      - name: Deploy WPF application
        run: |
          # Add your deployment commands here

      - name: Notify Deployment Success
        if: success()
        run: |
          $payload = '{"text": "🚀 Deployment completed successfully on the self-hosted Windows runner!"}'
          Invoke-RestMethod -Uri "${{ secrets.WEBHOOK_GITHUB_SLACK }}" -Method Post -Body $payload -ContentType 'application/json'
        shell: pwsh

      - name: Notify Deployment Failure
        if: failure()
        run: |
          $payload = '{"text": "❌ Deployment failed! Check logs for details."}'
          Invoke-RestMethod -Uri "${{ secrets.WEBHOOK_GITHUB_SLACK }}" -Method Post -Body $payload -ContentType 'application/json'
        shell: pwsh
