name: Temperature Converter CI/CD

on:
  push:
    branches:
      - "Temperature-Converter"
  pull_request:
    branches:
      - "Temperature-Converter"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build WPF application
        run: ./Temperature_Converter/build.ps1
        working-directory: ./

      - name: Verify output directory
        run: ls ./Temperature_Converter/output

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./Temperature_Converter/output

  test:
   needs: build
   runs-on: windows-latest

   steps:
    - uses: actions/checkout@v2
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: ./Temperature_Converter/output

    - name: Ensure TestResults directory exists
      run: mkdir -p TemperatureConverter/Temperature_Converter_UnitTest/TestResults

    - name: Run tests
      run: dotnet test ./TemperatureConverter/Temperature_Converter_UnitTest/Temperature_Converter_UnitTest.csproj --logger "junit;LogFilePath=TemperatureConverter/Temperature_Converter_UnitTest/TestResults/junit-unit-test-results.xml"

    - name: List TestResults directory
      run: ls TemperatureConverter/Temperature_Converter_UnitTest/TestResults

    - name: Upload unit test results
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: TemperatureConverter/Temperature_Converter_UnitTest/TestResults/junit-unit-test-results.xml
        if-no-files-found: warn
