name: WPF Build

on:
  push:
    branches:
      - "Temperature-Converter"
  pull_request:
    branches:
      - "Temperature-Converter"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build WPF application
        run: ./Temperature_Converter/build.ps1
        working-directory: ./

      - name: Verify output directory
        run: ls ./Temperature_Converter/output

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./Temperature_Converter/output

  test:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./output
      - name: Restore packages
        run: dotnet restore ./Temperature_Converter/Temperature_Converter.csproj
        working-directory: ./
      - name: Run unit tests and generate JUnit XML report
        run: dotnet test ./Temperature_Converter/Temperature_Converter.csproj --test-adapter-path:. --logger:"junit;LogFilePath=${{ env.TEST_RESULT_PATH }}"
        working-directory: ./
        env:
          TEST_RESULT_PATH: ./TestResults/junit-unit-test-results.xml
      - name: Upload unit test results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
          path: ./TestResults/junit-unit-test-results.xml
   
  deploy:
    needs:
      - build
      - test
    runs-on: [self-hosted, windows]

    steps:
      - uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ${{ github.workspace }}/output
      - name: Deploy WPF application
        run: |
          # Add your deployment commands here
